name: env_tutorial
on: [push] 

jobs:
  job1:
    runs-on: macos-latest 
    steps:
      - name: step 1
        run: |
          echo "The job ID is ${{env.github_job}}"   
          echo "The name of the workflow is ${{env.github_workflow}}" 
