name: Secrets Workflow

on: [push]

jobs:
  environment: Secret
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands with a Secret
        env:
            SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
        run: |
          echo "Hello World!"
          echo $SECRET_VALUE